export const FIELD_LABELS: Record<string, string> = {
  // Inspection — member / property
  homeownerName:          "Homeowner Name",
  homeownerEmail:         "Homeowner Email",
  homeownerEmail2:        "Homeowner Email 2",
  homeownerPhone:         "Homeowner Phone",
  propertyAddress:        "Property Address",
  propertyAddress2:       "Property Address 2",
  city:                   "City",
  county:                 "County",
  state:                  "State",
  zip:                    "ZIP",
  // Inspection — realtor
  realtorInvolved:        "Realtor Involved",
  requestedByRealtor:     "Requested by Realtor",
  realtorName:            "Realtor Name",
  realtorEmail:           "Realtor Email",
  realtorPhone:           "Realtor Phone",
  realtorPhoneType:       "Realtor Phone Type",
  // Inspection — inspector
  inspectorName:          "Inspector Name",
  inspectionCompany:      "Inspection Company",
  inspectionDate:         "Inspection Date",
  // Inspection — well system
  wellType:               "Well Type",
  wellDepthFt:            "Well Depth (ft)",
  wellDepthUnknown:       "Well Depth Unknown",
  pumpType:               "Pump Type",
  pumpManufacturer:       "Pump Manufacturer",
  pumpHp:                 "Pump HP",
  wellCompletionDate:     "Well Completion Date",
  wellCompletionDateUnknown: "Well Completion Date Unknown",
  wellPermit:             "Well Permit",
  wellPermitUnknown:      "Well Permit Unknown",
  wellDataSource:         "Well Data Source",
  wellObstructions:       "Well Obstructions",
  wellCap:                "Well Cap",
  casingHeightInches:     "Casing Height (in)",
  casingType:             "Casing Type",
  casingSize:             "Casing Size",
  distanceFromHouseFt:    "Distance from House (ft)",
  // Inspection — internal equipment
  amperageReading:        "Amperage Reading",
  tankCondition:          "Tank Condition",
  tankBrand:              "Tank Brand",
  tankModel:              "Tank Model",
  tankSizeGal:            "Tank Size (gal)",
  psiSettings:            "PSI Settings",
  controlBoxCondition:    "Control Box Condition",
  waterTreatment:         "Water Treatment",
  wireType:               "Wire Type",
  pressureSwitch:         "Pressure Switch",
  pressureGauge:          "Pressure Gauge",
  constantPressureSystem: "Constant Pressure System",
  // Inspection — yield test
  yieldTestType:          "Yield Test Type",
  secondsToHighReading:   "Seconds to High Reading",
  secondsToLowReading:    "Seconds to Low Reading",
  wellCalculationVersion: "Calculation Version",
  // Inspection — notes / review
  inspectorNotes:         "Inspector Notes",
  internalReviewerNotes:  "Internal Reviewer Notes",
  requiredRepairs:        "Required Repairs",
  recommendedRepairs:     "Recommended Repairs",
  memberFacingSummary:    "Member-Facing Summary",
  activity:               "Activity",
  finalStatus:            "Final Status",
  overrideReason:         "Override Reason",
  isDraft:                "Draft Status",
  // Service ticket — member
  memberFirstName:        "First Name",
  memberLastName:         "Last Name",
  memberEmail:            "Member Email",
  memberAltEmail:         "Member Alt Email",
  memberPhone:            "Member Phone",
  memberPhoneType:        "Member Phone Type",
  memberAltPhone:         "Member Alt Phone",
  memberAltPhoneType:     "Member Alt Phone Type",
  // Service ticket — address
  streetAddress:          "Street Address",
  streetAddress2:         "Street Address 2",
  // Service ticket — core
  serviceType:            "Service Type",
  status:                 "Status",
  callReceivedAt:         "Call Received At",
  scheduledFor:           "Scheduled For",
  lastServiceDate:        "Last Service Date",
  serviceCompletedBy:     "Service Completed By",
  callInNumber:           "Call-In Number",
  customerInquiry:        "Customer Inquiry",
  customerFollowUp:       "Customer Follow-Up",
  specialInstructions:    "Special Instructions",
  // Service ticket — checklist
  rightOfFirstRefusal:    "Right of First Refusal",
  valvesOpen:             "Valves Open",
  filterClogged:          "Filter Clogged",
  circuitBreakerReset:    "Circuit Breaker Reset",
  lowPressureSwitch:      "Low Pressure Switch",
  backwashCycle:          "Backwash Cycle",
  // Service ticket — tech
  faultIdentified:        "Fault Identified",
  repairsPerformed:       "Repairs Performed",
  technicianResponse:     "Technician Response",
  yieldValue:             "Yield Value",
  depthPerCustomer:       "Depth per Customer",
  // Service ticket — invoice
  invoiceNumber:          "Invoice Number",
  invoiceAmount:          "Invoice Amount",
  invoicePaymentType:     "Invoice Payment Type",
  invoiceAttachment:      "Invoice Attachment",
  servicePrice:           "Service Price",
  isComplete:             "Completed",
  completedBy:            "Completed By",
  // Vendor
  companyName:            "Company Name",
  vendorType:             "Vendor Type",
  primaryContact:         "Primary Contact",
  email:                  "Email",
  phone:                  "Phone",
  phone2:                 "Phone 2",
  licenseNumber:          "License Number",
  rating:                 "Rating",
  notes:                  "Notes",
  websiteUrl:             "Website URL",
  ghlReferenceId:         "GHL Reference ID",
  // Inspector
  name:                   "Name",
  company:                "Company",
  yearsExperience:        "Years of Experience",
  licenseStates:          "License States",
  certifications:         "Certifications",
  // User
  role:                   "Role",
  mustChangePassword:     "Must Change Password",
};

export function fieldLabel(field: string): string {
  return FIELD_LABELS[field] ?? field.replace(/([A-Z])/g, " $1").trim();
}
